---
#collections:
#  - name: 
#    source: https://galaxy.ansible.com

#  - name: f5networks.f5_modules
#    source: https://cloud.redhat.com/api/automation-hub/

#  - name: vmware.vmware_rest

# - name: community.general

roles:
  # Install a role from Ansible Galaxy.
  - name: geerlingguy.ntp
