---
- name: Install Heartbeat.
  package:
    name: "{{ heartbeat_package }}"
    state: "{{ heartbeat_package_state }}"

- name: Copy Heartbeat configuration.
  template:
    src: "{{ heartbeat_template }}"
    dest: "/etc/{{ heartbeat_package }}/heartbeat.yml"
    owner: root
    group: root
    mode: 0644
  when: heartbeat_create_config | bool 
  notify: restart heartbeat

- name: Ensure Heartbeat is started and enabled at boot.
  service:
    name: heartbeat
    state: started
    enabled: true