---
- name: Config - Install Filebeat.
  package:
    name: "{{ filebeat_package }}"
    state: "{{ filebeat_package_state }}"

- name: Config - Copy Filebeat configuration.
  template:
    src: "{{ filebeat_template }}"
    dest: "/etc/{{ filebeat_package }}/filebeat.yml"
    owner: root
    group: root
    mode: 0644
  when: filebeat_create_config | bool
  notify: restart filebeat

- name: Enable and configure System Module
  command: filebeat modules enable system

- name: Config - Run services_facts
  service_facts:

- name: Config - Check for service
  #debug:
  #  msg: "apache2 is {{ ansible_facts.services['apache2.service']['status'] }}"
  command: filebeat modules enable apache
  when: "'apache2.service' in ansible_facts.services"

- name: Ensure Filebeat is started and enabled at boot.
  service:
    name: filebeat
    state: started
    enabled: true